/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobCategory = IDL.Variant({
  'marketing' : IDL.Null,
  'design' : IDL.Null,
  'writing' : IDL.Null,
  'development' : IDL.Null,
  'dataEntry' : IDL.Null,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : JobCategory,
  'requirements' : IDL.Text,
  'payRate' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'completedJobs' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
  'skills' : IDL.Vec(IDL.Text),
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'appliedAt' : IDL.Int,
  'jobId' : IDL.Nat,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, JobCategory, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobApplications' : IDL.Func([IDL.Nat], [IDL.Vec(Application)], ['query']),
  'getOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getTopEarners' : IDL.Func([IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
  'getUserApplications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        JobCategory,
        IDL.Float64,
        IDL.Text,
        JobStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobCategory = IDL.Variant({
    'marketing' : IDL.Null,
    'design' : IDL.Null,
    'writing' : IDL.Null,
    'development' : IDL.Null,
    'dataEntry' : IDL.Null,
  });
  const JobStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : JobCategory,
    'requirements' : IDL.Text,
    'payRate' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'completedJobs' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'appliedAt' : IDL.Int,
    'jobId' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, JobCategory, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getTopEarners' : IDL.Func([IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
    'getUserApplications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          JobCategory,
          IDL.Float64,
          IDL.Text,
          JobStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };