/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'applicant' : Principal,
  'appliedAt' : bigint,
  'jobId' : bigint,
  'updatedAt' : bigint,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'title' : string,
  'creator' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'category' : JobCategory,
  'requirements' : string,
  'payRate' : number,
}
export type JobCategory = { 'marketing' : null } |
  { 'design' : null } |
  { 'writing' : null } |
  { 'development' : null } |
  { 'dataEntry' : null };
export type JobStatus = { 'closed' : null } |
  { 'open' : null };
export interface UserProfile {
  'bio' : string,
  'completedJobs' : bigint,
  'totalEarnings' : number,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<
    [string, string, JobCategory, number, string],
    bigint
  >,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getJobApplications' : ActorMethod<[bigint], Array<Application>>,
  'getOpenJobs' : ActorMethod<[], Array<Job>>,
  'getTopEarners' : ActorMethod<[bigint], Array<UserProfile>>,
  'getUserApplications' : ActorMethod<[Principal], Array<Application>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, JobCategory, number, string, JobStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];